name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository Checkout
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Docker Build & Push
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ptf-was:1.0
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # 3. Prepare SSH Key for Google Cloud
    - name: Prepare SSH Key
      run: |
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > gcp-key.pem
        chmod 600 gcp-key.pem

    # 4. Deploy to Google Cloud
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.GCP_SERVER_IP }}
        username: ${{ secrets.GCP_SSH_USERNAME }}
        key: gcp-key.pem
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ptf-was:1.0
          docker-compose -f ${{ secrets.COMPOSE_FILE_PATH }} up -d
